pytest: use --strict (#5966)
This causes errors with invalid markers:

> AttributeError: 'skipUnless' not a registered marker

Fixed in https://github.com/encode/django-rest-framework/pull/5965.